-- Lifetime Research Quota authority. Run admission and settlement are kept in
-- database RPCs so later Agent Run work cannot recreate the balance in a
-- browser or in a Worker-local state machine.

create table public.research_quotas (
  owner_id uuid primary key references public.profiles(id) on delete cascade,
  lifetime_units integer not null default 0 check (lifetime_units >= 0),
  reserved_units integer not null default 0 check (reserved_units >= 0),
  settled_units integer not null default 0 check (settled_units >= 0),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  check (lifetime_units >= reserved_units + settled_units)
);

create table public.research_quota_reservations (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  request_id text not null check (length(btrim(request_id)) between 1 and 160),
  units integer not null default 1 check (units = 1),
  status text not null default 'reserved' check (status in ('reserved', 'committed', 'released')),
  created_at timestamptz not null default timezone('utc', now()),
  resolved_at timestamptz,
  unique (id, owner_id)
);

create table public.research_quota_ledger (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references public.profiles(id) on delete cascade,
  reservation_id uuid,
  actor_id uuid references public.profiles(id) on delete set null,
  event_type text not null check (event_type in ('admin_adjustment', 'reservation', 'commit', 'release')),
  request_id text,
  reason text not null check (length(btrim(reason)) between 1 and 500),
  lifetime_before integer not null check (lifetime_before >= 0),
  lifetime_after integer not null check (lifetime_after >= 0),
  reserved_before integer not null check (reserved_before >= 0),
  reserved_after integer not null check (reserved_after >= 0),
  settled_before integer not null check (settled_before >= 0),
  settled_after integer not null check (settled_after >= 0),
  created_at timestamptz not null default timezone('utc', now()),
  foreign key (reservation_id, owner_id) references public.research_quota_reservations(id, owner_id),
  check (lifetime_after >= reserved_after + settled_after)
);

create index research_quota_reservations_owner_status_idx
  on public.research_quota_reservations (owner_id, status, created_at desc);
create unique index research_quota_reservations_request_idx
  on public.research_quota_reservations (owner_id, request_id);
create index research_quota_ledger_owner_created_idx
  on public.research_quota_ledger (owner_id, created_at desc, id desc);

create trigger research_quotas_set_updated_at
before update on public.research_quotas
for each row execute function public.set_updated_at();

create or replace function public.research_quota_snapshot(
  p_owner_id uuid,
  p_idempotent boolean default false
)
returns jsonb
language sql
stable
security invoker
set search_path = public
as $$
  select jsonb_build_object(
    'owner_id', q.owner_id,
    'lifetime_units', q.lifetime_units,
    'reserved_units', q.reserved_units,
    'settled_units', q.settled_units,
    'available_units', q.lifetime_units - q.reserved_units - q.settled_units,
    'updated_at', q.updated_at,
    'idempotent', p_idempotent
  )
  from public.research_quotas q
  where q.owner_id = p_owner_id;
$$;

create or replace function public.admin_adjust_research_quota(
  p_owner_id uuid,
  p_lifetime_units integer,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor_id uuid := auth.uid();
  v_quota public.research_quotas%rowtype;
begin
  if v_actor_id is null or not public.is_admin() then
    raise exception 'forbidden' using errcode = '42501';
  end if;
  if p_lifetime_units is null or p_lifetime_units < 0
     or p_reason is null or length(btrim(p_reason)) = 0 or length(btrim(p_reason)) > 500 then
    raise exception 'invalid_quota_adjustment' using errcode = '22023';
  end if;
  if not exists (select 1 from public.profiles where id = p_owner_id and role = 'user') then
    raise exception 'research_quota_target_not_found' using errcode = 'P0001';
  end if;

  insert into public.research_quotas (owner_id)
  values (p_owner_id)
  on conflict (owner_id) do nothing;
  select * into v_quota
  from public.research_quotas
  where owner_id = p_owner_id
  for update;

  if p_lifetime_units < v_quota.reserved_units + v_quota.settled_units then
    raise exception 'research_quota_below_committed' using errcode = 'P0001';
  end if;

  update public.research_quotas
  set lifetime_units = p_lifetime_units
  where owner_id = p_owner_id;

  insert into public.research_quota_ledger (
    owner_id, actor_id, event_type, reason,
    lifetime_before, lifetime_after,
    reserved_before, reserved_after,
    settled_before, settled_after
  ) values (
    p_owner_id, v_actor_id, 'admin_adjustment', btrim(p_reason),
    v_quota.lifetime_units, p_lifetime_units,
    v_quota.reserved_units, v_quota.reserved_units,
    v_quota.settled_units, v_quota.settled_units
  );

  return public.research_quota_snapshot(p_owner_id);
end;
$$;

create or replace function public.reserve_research_quota(p_request_id text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_owner_id uuid := auth.uid();
  v_quota public.research_quotas%rowtype;
  v_reservation public.research_quota_reservations%rowtype;
begin
  if v_owner_id is null then
    raise exception 'unauthorized' using errcode = '42501';
  end if;
  if p_request_id is null or length(btrim(p_request_id)) = 0 or length(btrim(p_request_id)) > 160 then
    raise exception 'invalid_quota_request' using errcode = '22023';
  end if;

  insert into public.research_quotas (owner_id)
  values (v_owner_id)
  on conflict (owner_id) do nothing;
  select * into v_quota
  from public.research_quotas
  where owner_id = v_owner_id
  for update;

  select * into v_reservation
  from public.research_quota_reservations
  where owner_id = v_owner_id and request_id = btrim(p_request_id)
  for update;
  if found then
    return (public.research_quota_snapshot(v_owner_id, true) || jsonb_build_object(
      'reservation_id', v_reservation.id,
      'request_id', v_reservation.request_id,
      'status', v_reservation.status
    ));
  end if;

  if v_quota.lifetime_units - v_quota.reserved_units - v_quota.settled_units < 1 then
    raise exception 'research_quota_insufficient' using errcode = 'P0001';
  end if;

  insert into public.research_quota_reservations (owner_id, request_id)
  values (v_owner_id, btrim(p_request_id))
  returning * into v_reservation;

  update public.research_quotas
  set reserved_units = reserved_units + 1
  where owner_id = v_owner_id;

  insert into public.research_quota_ledger (
    owner_id, reservation_id, event_type, request_id, reason,
    lifetime_before, lifetime_after,
    reserved_before, reserved_after,
    settled_before, settled_after
  ) values (
    v_owner_id, v_reservation.id, 'reservation', v_reservation.request_id, 'agent_run_reservation',
    v_quota.lifetime_units, v_quota.lifetime_units,
    v_quota.reserved_units, v_quota.reserved_units + 1,
    v_quota.settled_units, v_quota.settled_units
  );

  return (public.research_quota_snapshot(v_owner_id) || jsonb_build_object(
    'reservation_id', v_reservation.id,
    'request_id', v_reservation.request_id,
    'status', v_reservation.status
  ));
end;
$$;

create or replace function public.commit_research_quota(p_reservation_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_owner_id uuid := auth.uid();
  v_quota public.research_quotas%rowtype;
  v_reservation public.research_quota_reservations%rowtype;
begin
  if v_owner_id is null then
    raise exception 'unauthorized' using errcode = '42501';
  end if;
  select * into v_quota from public.research_quotas where owner_id = v_owner_id for update;
  select * into v_reservation
  from public.research_quota_reservations
  where id = p_reservation_id and owner_id = v_owner_id
  for update;
  if not found then
    raise exception 'research_quota_reservation_not_found' using errcode = 'P0001';
  end if;
  if v_reservation.status <> 'reserved' then
    return (public.research_quota_snapshot(v_owner_id, true) || jsonb_build_object(
      'reservation_id', v_reservation.id,
      'request_id', v_reservation.request_id,
      'status', v_reservation.status
    ));
  end if;

  update public.research_quota_reservations
  set status = 'committed', resolved_at = timezone('utc', now())
  where id = v_reservation.id;
  update public.research_quotas
  set reserved_units = reserved_units - 1, settled_units = settled_units + 1
  where owner_id = v_owner_id;
  insert into public.research_quota_ledger (
    owner_id, reservation_id, event_type, request_id, reason,
    lifetime_before, lifetime_after,
    reserved_before, reserved_after,
    settled_before, settled_after
  ) values (
    v_owner_id, v_reservation.id, 'commit', v_reservation.request_id, 'agent_run_settlement',
    v_quota.lifetime_units, v_quota.lifetime_units,
    v_quota.reserved_units, v_quota.reserved_units - 1,
    v_quota.settled_units, v_quota.settled_units + 1
  );
  return (public.research_quota_snapshot(v_owner_id) || jsonb_build_object(
    'reservation_id', v_reservation.id,
    'request_id', v_reservation.request_id,
    'status', 'committed'
  ));
end;
$$;

create or replace function public.release_research_quota(p_reservation_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_owner_id uuid := auth.uid();
  v_quota public.research_quotas%rowtype;
  v_reservation public.research_quota_reservations%rowtype;
begin
  if v_owner_id is null then
    raise exception 'unauthorized' using errcode = '42501';
  end if;
  select * into v_quota from public.research_quotas where owner_id = v_owner_id for update;
  select * into v_reservation
  from public.research_quota_reservations
  where id = p_reservation_id and owner_id = v_owner_id
  for update;
  if not found then
    raise exception 'research_quota_reservation_not_found' using errcode = 'P0001';
  end if;
  if v_reservation.status <> 'reserved' then
    return (public.research_quota_snapshot(v_owner_id, true) || jsonb_build_object(
      'reservation_id', v_reservation.id,
      'request_id', v_reservation.request_id,
      'status', v_reservation.status
    ));
  end if;

  update public.research_quota_reservations
  set status = 'released', resolved_at = timezone('utc', now())
  where id = v_reservation.id;
  update public.research_quotas
  set reserved_units = reserved_units - 1
  where owner_id = v_owner_id;
  insert into public.research_quota_ledger (
    owner_id, reservation_id, event_type, request_id, reason,
    lifetime_before, lifetime_after,
    reserved_before, reserved_after,
    settled_before, settled_after
  ) values (
    v_owner_id, v_reservation.id, 'release', v_reservation.request_id, 'agent_run_release',
    v_quota.lifetime_units, v_quota.lifetime_units,
    v_quota.reserved_units, v_quota.reserved_units - 1,
    v_quota.settled_units, v_quota.settled_units
  );
  return (public.research_quota_snapshot(v_owner_id) || jsonb_build_object(
    'reservation_id', v_reservation.id,
    'request_id', v_reservation.request_id,
    'status', 'released'
  ));
end;
$$;

alter table public.research_quotas enable row level security;
alter table public.research_quota_reservations enable row level security;
alter table public.research_quota_ledger enable row level security;

grant select on public.research_quotas, public.research_quota_reservations, public.research_quota_ledger to authenticated;
grant select, insert, update, delete on public.research_quotas, public.research_quota_reservations, public.research_quota_ledger to service_role;
revoke insert, update, delete on public.research_quotas, public.research_quota_reservations, public.research_quota_ledger from authenticated;

create policy research_quotas_select on public.research_quotas
for select to authenticated using ((select auth.uid()) = owner_id or (select public.is_admin()));
create policy research_quota_reservations_select on public.research_quota_reservations
for select to authenticated using ((select auth.uid()) = owner_id or (select public.is_admin()));
create policy research_quota_ledger_select on public.research_quota_ledger
for select to authenticated using ((select auth.uid()) = owner_id or (select public.is_admin()));

revoke all on function public.research_quota_snapshot(uuid, boolean) from public, anon, authenticated;
revoke all on function public.admin_adjust_research_quota(uuid, integer, text) from public, anon, authenticated;
revoke all on function public.reserve_research_quota(text) from public, anon;
revoke all on function public.commit_research_quota(uuid) from public, anon;
revoke all on function public.release_research_quota(uuid) from public, anon;
grant execute on function public.admin_adjust_research_quota(uuid, integer, text) to authenticated;
grant execute on function public.reserve_research_quota(text) to authenticated;
grant execute on function public.commit_research_quota(uuid) to authenticated;
grant execute on function public.release_research_quota(uuid) to authenticated;
grant execute on function public.research_quota_snapshot(uuid, boolean) to service_role;
